# Generated by Django 3.2.23 on 2023-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestdbDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeofupload', models.DateTimeField(db_column='dateTimeofUpload')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('uploadedfile', models.CharField(blank=True, db_column='uploadedFile', max_length=100, null=True)),
            ],
            options={
                'db_table': 'testdb_document',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
