# Generated by Django 3.2.23 on 2023-12-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='attached',
        ),
        migrations.AddField(
            model_name='document',
            name='dateTimeofUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(default='', null=True, upload_to='result/'),
        ),
    ]
